apiVersion: one-click.dev/v1alpha1
kind: Rollout
metadata:
  name: streamlit
  namespace: demo-streamlit
spec:
  image:
    registry: "ghcr.io"
    repository: "janlauber/one-click-demo"
    tag: "0.1.0"
  horizontalScale:
    minReplicas: 2
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
  interfaces:
    - name: "http-streamlit"
      port: 8501
      ingress:
        ingressClass: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/rewrite-target: /
        rules:
          - host: "streamlit.demo.one-click.dev"
            path: "/"
            tls: false
  serviceAccountName: "streamlit"
