apiVersion: one-click.dev/v1alpha1
kind: Rollout
metadata:
  name: node-red
  namespace: demo-node-red
spec:
  image:
    registry: "docker.io"
    repository: "nodered/node-red"
    tag: "3.1.3"
  horizontalScale:
    minReplicas: 1
    maxReplicas: 3
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
  env:
    - name: "TZ"
      value: "Europe/Zurich"
  volumes:
    - name: "data"
      mountPath: "/data"
      size: "2Gi"
  interfaces:
    - name: "http-node-red"
      port: 1880
      ingress:
        ingressClass: "nginx"
        rules:
          - host: "node-red.demo.one-click.dev"
            path: "/"
            tls: false
