apiVersion: one-click.dev/v1alpha1
kind: Rollout
metadata:
  name: node-red
  namespace: demo-node-red
spec:
  image:
    registry: "docker.io"
    repository: "nodered/node-red"
    tag: "3.1.3"
    # username: "test"
    # password: "test3"
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    readOnlyRootFilesystem: true
    privileged: false
    capabilities:
      drop:
        - ALL
      add:
        - NET_BIND_SERVICE
  horizontalScale:
    minReplicas: 1
    maxReplicas: 1
    targetCPUUtilizationPercentage: 80
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
  env:
    - name: "TZ"
      value: "Europe/Zurich"
  # secrets:
  #   - name: "REFLEX_PASSWORD"
  #     value: "admin"
  #   - name: "ANOTHER_SECRET"
  #     value: "122"
  volumes:
    - name: "data"
      mountPath: "/data"
      size: "2Gi"
      storageClass: "standard-rwo"
  interfaces:
    - name: "http-node-red"
      port: 1880
      ingress:
        ingressClass: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/rewrite-target: /
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          # cert-manager.io/cluster-issuer: letsencrypt-prod
          # cert-manager.io/private-key-rotation-policy: "Always"
        rules:
          - host: "node-red.demo.one-click.dev"
            path: "/"
            tls: false
  serviceAccountName: "nginx"
